### PR TITLE
issue #26385 - QR Codes and PDF417 for OpenRPT!

### PR DESCRIPTION
**Pull request by davidbeauchamp**
Implements the [Zint](https://github.com/zint/zint) barcode library with option screens created for PDF417 and QR Codes since those are the big two, but any [symbology Zint supports](http://zint.org.uk/) can easily be included.

### CODE REVIEW

**Comment by davidbeauchamp** [comment]
Ahh right, there is no QJsonDocument in qt4... so.. conditional around it, knowing that we don't build with Qt4 anymore?

**Comment by gilmoskowitz** [comment]
[zint is GPL3](https://sourceforge.net/p/zint/code/ci/master/tree/COPYING), which is too restrictive for use by OpenRPT and xTuple ERP. Either we need to wrap the [zint backend](https://sourceforge.net/p/zint/code/ci/master/tree/backend/LICENSE), find another library, or roll our own.

**Comment by davidbeauchamp** [comment]
This is my mistake, what this is is a wrapper for the zint library itself (aka the backend). I committed the wrong license.

**Comment by nedlilly** [comment]
Whew.  Thanks, guys.

**Pull request merged**
